function TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)

fig1 = figure('Name','Tranzistor Baza Comuna',...
       'Units','normalized',...
       'Position',[0.1 0.1 0.7 0.8],...  % creare figura
       'NumberTitle','off',...
       'Color', '#faf7ac');

f1=uimenu('Label','Documentatie');
uimenu(f1,'Label','Documentatie Word','Callback','open(''DocumentatieWord.htm'')');         % Documentatie
uimenu(f1,'Label','Prezentare Proiect','Callback','open(''PrezentareProiect.pptx'')');  

uicontrol('Style','PopupMenu',...         % Amplificator / PSF PopUpMenu
          'Units','normalized',...
          'Position',[0.75 0.95 0.15 0.04],...
          'String','Amplificator|PSF',...
          'BackgroundColor', '#cc7416',...
          'FontSize', 15,...
          'Value',val,...
          'Callback','val=get(gcbo,''Value''),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');

uicontrol('Units', 'normalized',...
          'Position', [0.78 0.05 0.2 0.1],...
          'BackgroundColor', 'r',...
          'String', 'Închide aplicația',...                      % Close aplication button
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'ForegroundColor', 'w',...
          'Callback', "close('all','hidden')"); 
      
x = imread('img2.jpg');                                             %inserare schema electrica
subplot('Position', [0.01 0.08 0.45 0.45])  , imshow(x);      

%{
......
DATE DE INTRARE INTERFATA GRAFICA
......
%}

uicontrol('Style','text', ...        % DateDeIntrare TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.07 0.9 0.12 0.07], ...
          'String','Date de intrare',...
          'BackgroundColor', '#cc7416',...
          'FontSize', 15);

uicontrol('Style','text', ...   % R1 TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.84 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','R1 = ');
      
uicontrol('Style','edit',...     % R1 EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.84 0.1 0.03],...
          'String',R1,...
          'Callback','R1=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
uicontrol('Style','text', ...   % R2 TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.78 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','R2 = ');
      
uicontrol('Style','edit',...     % R2 EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.78 0.1 0.03],...
          'String',R2,...
          'Callback','R2=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');

uicontrol('Style','text', ...   % RC TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.72 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','RC = ');
      
uicontrol('Style','edit',...     % RC EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.72 0.1 0.03],...
          'String',RC,...
          'Callback','RC=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
uicontrol('Style','text', ...   % Re TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.66 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','RE = ');
      
uicontrol('Style','edit',...     % Re EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.66 0.1 0.03],...
          'String',RE,...
          'Callback','RE=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
uicontrol('Style','text', ...   % Rs TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.6 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Rs = ');
      
uicontrol('Style','edit',...     % Rs EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.6 0.1 0.03],...
          'String',Rs,...
          'Callback','Rs=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
uicontrol('Style','text', ...   % VCC TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.05 0.54 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','VCC = ');
      
uicontrol('Style','edit',...     % VCC EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.1 0.54 0.1 0.03],...
          'String',VCC,...
          'Callback','VCC=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');      
      
%{
......
Calculare Date de Iesire
......
%} 
   
   Vbe = 0.7;
   B = 250;
   VB = (R2./(R1+R2))*VCC;
   VE = VB - 0.7;
   IE = VE ./ RE;
   Rin = 0.025 ./ IE;    % rezistenta de intrare
   Rc = (RC.*Rs)./(RC + Rs);
   Av = Rc ./ Rin;  % castigul in tensiune
   Ai = 1;          % castigul in curent
   Ap = Av;         % castigul in putere
   Vce = VCC - IE * RC;
   Ic = IE;
   gm = 40 * Ic;
   
%{
........
Afisare Date de Iesire
........
%}

uicontrol('Style','text', ...        % DateDeIesire TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.33 0.9 0.12 0.07], ...
          'String','Date de iesire',...
          'BackgroundColor', '#cc7416',...
          'FontSize', 15);
      
uicontrol('Style','text', ...   % Rin TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.3 0.84 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Rin = ');
      

uicontrol('Style','edit',... % Afisare Rin
          'Units','normalized',...
          'Position',[0.35 0.84 0.1 0.03],...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String',Rin,...
          'Enable','off'); 
      
uicontrol('Style','text', ...   % Ωohm TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.45 0.84 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 12,...
          'String','[Ω]');
      
uicontrol('Style','text', ...   % Av TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.3 0.78 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Av = ');
      
uicontrol('Style','edit',... % Afisare Av
          'Units','normalized',...
          'Position',[0.35 0.78 0.1 0.03],...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String',Av,...
          'Enable','off'); 
      
uicontrol('Style','text', ...   % Ai TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.3 0.72 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Ai = ');
      
uicontrol('Style','edit',... % Afisare Ai
          'Units','normalized',...
          'Position',[0.35 0.72 0.1 0.03],...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String',Ai,...
          'Enable','off'); 

%{
........
Semnalul de intrare
........
%}
if(val==1)
   uicontrol('Style','text', ...        % ParametriSemnalIntrare TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.45 0.55 0.15 0.07], ...
          'String','Parametri Semnal Intrare',...
          'BackgroundColor', '#cc7416',...
          'FontSize', 15);
      
    uicontrol('Style','text', ...   % A TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.45 0.49 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','A = ');
      
uicontrol('Style','edit',...     % A EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.50 0.49 0.1 0.03],...
          'String',A,...
          'Callback','A=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
uicontrol('Style','text', ...   % f TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.45 0.43 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','f = ');
      
uicontrol('Style','edit',...     % f EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.50 0.43 0.1 0.03],...
          'String',f,...
          'Callback','f=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');

uicontrol('Style','text', ...   % N TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.45 0.37 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','N = ');
      
uicontrol('Style','edit',...     % N EDIT
          'Units','normalized',...
          'backgroundcolor',[1 1 1],...
          'Position',[0.50 0.37 0.1 0.03],...
          'String',N,...
          'Callback','N=str2num(get(gco,''String'')),close;TranzistorProiectFunction2(R1, R2, RC, RE, Rs, VCC,f ,N, A, val)');
      
   T = 1 ./ f;
   t = 0 : T / 100 : N *T;
   vi = A * sin(2 .* pi .* f .* t);
   subplot('Position', [0.68 0.6 0.29 0.29])                      % plotare semnal intrare
   plot(t, vi);
   grid on; hold on;
   title('Semnalul de intrare') ;
   ylabel('A, [V]') ;

%{
........
Semnalul de iesire
........
%}
vout = Av * vi;
subplot('Position', [0.68 0.24 0.29 0.29])
plot(t, vout);
grid on;
title('Semnalul de iesire') ;                                      % plotare vout
xlabel('T, [s]') ;
ylabel('A, [V]') ;   
end

%{
......
PSF
......
%}
if(val==2)
    
x = imread('img3.jpg');                                             %inserare schema electrica echivalent in cc
subplot('Position', [0.65 0.55 0.35 0.35])  , imshow(x);

uicontrol('Style','text', ...   % Ic TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.42 0.4 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Ic = ');
      

uicontrol('Style','edit',... % Afisare Ic
          'Units','normalized',...
          'Position',[0.47 0.4 0.1 0.03],...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String',Ic*10.^3,...
          'Enable','off');
      
uicontrol('Style','text', ...   % mA TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.57 0.4 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 12,...
          'String','[mA]');
      
uicontrol('Style','text', ...   % Vce TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.42 0.35 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String','Vce = ');
      

uicontrol('Style','edit',... % Afisare Vce
          'Units','normalized',...
          'Position',[0.47 0.35 0.1 0.03],...
          'FontName', 'Calibri Light',...
          'FontSize', 15,...
          'String',Vce,...
          'Enable','off');
      
uicontrol('Style','text', ...   % V TEXT
          'Units','normalized', ...
          'backgroundcolor',[1 1 1],...
          'Position',[0.57 0.35 0.05 0.03], ...
          'FontName', 'Calibri Light',...
          'FontSize', 12,...
          'String','[V]');
      
Icma = Ic*10.^3;   
subplot('Position', [0.68 0.22 0.29 0.29])      
plot(Vce,Icma,'ro','MarkerSize',12); hold on;
plot([Vce,Vce,0],[0,Icma,Icma], 'k--'); hold on;                % plotare PSF
grid on;
xlabel('Vce [V]');
ylabel('Ic [mA]');
end
%{
......
Mesaj eroare in caz de valori negative
......
%}

if (R1 <= 0 || R2 <= 0 || RC <= 0 || RE <= 0 || Rs <= 0)
    msgbox('Introduceti o valoare pozitiva!'); 
    close('Tranzistor Baza Comuna');
end


  